### ISSUE TITLE
[FEATURE] User controlled Auto Redirection

### ISSUE THREAD

**Issue by msaindane** [Lavakumar/IronWASP#4]
Ability for user to set custom options in Automated Scanning and Manual Testing tabs to automatically follow 30x redirects, with fine grain control. 

E.g. follow only 302 and not 301. Follow redirect based on URL regex in Location header, etc.

**Comment by Lavakumar** [comment]
For Automated Scanning Session Plugins take care of this. Session Plugin creation assistant specially asks for this so that user can configure this without writing any code.

For Manual Testing there is 'Follow Redirect' and 'Get Redirect' buttons that the user can click to follow redirects in response. Ofcourse for advanced users 'Scripted Send' feature gives more options to customize and automate this behaviour.
